_target_: src.detector.Detector
name: dlib68
model:
  _target_: src.detector.DlibDetector
  model_path: ./weights/dlib/shape_predictor_68_face_landmarks.dat
  detector_name: "HOG+LinearSVM"
  detector_path:
  device:
