shuffle: False
num_workers: 4
pin_memory: True
drop_last: False

train:
  _target_: torch.utils.data.DataLoader
  dataset: ${dataset}
  batch_size: ???
  shuffle: ${dataloader.shuffle}
  num_workers: ${dataloader.num_workers}
  pin_memory: ${dataloader.pin_memory}
  drop_last: ${dataloader.drop_last}

test:
  _target_: torch.utils.data.DataLoader
  dataset: ${dataset.test}
  batch_size: ???
  shuffle: False
  num_workers: ${dataloader.num_workers}
  pin_memory: ${dataloader.pin_memory}
  drop_last: ${dataloader.drop_last}
