defaults:
  - dataloader: loader
  - dataset:
  - detector: Identity
  - encoder:
  - runner:
  - transform:
  - _self_

checkpoint:
author: iccv-anonymous

dataloader:
  num_workers: 0
  batch_size: 1

resume: True
verbose: False

hydra.job.chdir: False
